language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t docker-react-aws -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react-aws npm run test

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-react-aws-app
  env: Dockerreactawsapp-env
  bucket_name: elasticbeanstalk-us-east-1-784712499272
  bucket_path: docker-react-aws-app-myfolder
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"